### ISSUE TITLE
echarts4r e_map New Zealand map too small

### ISSUE THREAD

**Issue by MinhChauVanNguyen** [JohnCoene/echarts4r.maps#4]
Hi John,

I am having trouble with enlarging the map for New Zealand.  The following code works fine for every country but not for New Zealand. 

```
e_charts() %>%
  em_maps(c("China", "Japan", "India"), "user") %>%
  e_map(map = "user")

e_charts() %>%
  em_maps("New_Zealand", "user") %>%
  e_map(map = "user", layoutSize = "150px")
```

More specifically, the maps for other countries are shown in normal size but the map of New Zealand appears to be very small and you can barely see it as shown in the screenshot. 

<img width="1201" alt="Screen Shot 2020-05-16 at 6 55 55 PM" src="https://user-images.githubusercontent.com/61895317/82113164-ed9c5680-97a7-11ea-94c0-fe2cbfb12bd6.png">

Any help for the problem behind this issue would be greatly appreciated. I also would like to add I'd been enjoying using this package very much, the charts produced are helpful and they look amazing so thank you heaps.

Thanks again,

Minh

**Comment by JohnCoene** [comment]
The issue here are the islands of Chatham, you could just remove them from the underlying GeoJSON used by echarts4r.maps.

```r
library(echarts4r)
library(echarts4r.maps)

nz_file <- system.file("New_Zealand.json", package = "echarts4r.maps") 
nz_json <- jsonlite::read_json(nz_file)

# identify polygon causing issues
library(purrr)

# get names of polygons
names <- nz_json$features %>% 
  map("properties") %>% 
  map("name") %>% 
  unlist()

island_index <- grep("Chatham", names)

nz_json$features[[island_index]] <- NULL

e_charts() %>%
  e_map_register("NZ", nz_json) %>%
  e_map(map = "NZ")
``` 

Does this help?

**Comment by MinhChauVanNguyen** [comment]
Hi John,

That works perfectly. Thank you very much for your fast reply and help!
